application: platxo-bi
version: development
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /static
  static_dir: static

- url: /.*
  script: platxo.wsgi.application

skip_files:
- manage.py
- requirements.txt
- (.*)\.pyc
- (.*)\.db
- (.*)\-info
- README.md
- .gitignore
